### ISSUE TITLE
Block Element Modifier - Element Modifier

### ISSUE THREAD

**Issue by TomS-** [getbem/getbem.com#98] opened 2016-07-12 16:09 UTC
Hey,

Noticed the last few questions haven't been answered in almost a month. Is this still active? 

I was wondering what would be the correct way to do the following
**html:**
`<div class="intro">
     <span class="intro__span--title"></span>
     <span class="intro__span"></span>
     <span class="intro__span"></span>
</div>`
**css:**
`intro__span {
    display: block;
}
intro__span--title {
   font-size: 1.3em;
}`
intro__span--title doesn't take on intro__span so to do a modifier would you have to do the following?
`<span class="intro__span intro__span--title"></span>`

**Comment by floatdrop** [comment] 2016-08-03 13:04
Duplicate of #99

**Closed by floatdrop** 2016-08-03 13:04 UTC
